import type {
  StaffUser,
  PropertyQcItem,
  OrgVerificationItem,
  UserAccountItem,
  AdminBillingOrder,
  AdminAuditLog,
  AdminOverviewStats,
  AdminRefundCase,
  AdminDisputeCase,
  AdminContactUnlockTrace,
  AdminFraudAlert,
  AdminGovernanceSettings,
} from "./types";

export const DEFAULT_GOVERNANCE_SETTINGS: AdminGovernanceSettings = {
  propertyReviewPolicy: "AI_SMART_TRIAGE",
  orgReviewPolicy: "MANDATORY_KYC",
  autoAssignEnabled: true,
  routingStrategy: "LEAST_LOADED",
  maxActiveTicketsPerAgent: 12,
  duplicateGeofenceRadiusMeters: 100,
  rateAnomalyThresholdPercent: 35,
  autoDisputeLeadRefundLimitHours: 24,
  requireTwoPersonRefundApproval: true,
  updatedAt: "2026-09-30T10:00:00Z",
  updatedByStaffName: "Vinay Kumar (Super Admin)",
};

export const INITIAL_STAFF_MEMBERS: StaffUser[] = [
  {
    id: 1,
    name: "Vinay Kumar",
    email: "vinay.admin@awasio.in",
    roles: ["SUPER_ADMIN"],
    status: "ACTIVE",
    mfaEnabled: true,
    lastLoginAt: "2026-09-30T14:00:00Z",
    createdAt: "2026-01-15T09:00:00Z",
  },
  {
    id: 2,
    name: "Rajesh Sharma",
    email: "rajesh.ops@awasio.in",
    roles: ["OPERATIONS_MANAGER"],
    status: "ACTIVE",
    mfaEnabled: true,
    lastLoginAt: "2026-09-30T13:00:00Z",
    createdAt: "2026-02-01T10:00:00Z",
  },
  {
    id: 3,
    name: "Pooja Batra",
    email: "pooja.lead@awasio.in",
    roles: ["SENIOR_QC_LEAD", "QC_REVIEWER"],
    status: "ACTIVE",
    mfaEnabled: true,
    lastLoginAt: "2026-09-30T12:45:00Z",
    createdAt: "2026-02-15T11:00:00Z",
  },
  {
    id: 4,
    name: "Anjali Mehta",
    email: "anjali.qc@awasio.in",
    roles: ["QC_REVIEWER"],
    status: "ACTIVE",
    mfaEnabled: true,
    lastLoginAt: "2026-09-30T12:30:00Z",
    createdAt: "2026-03-10T11:30:00Z",
  },
  {
    id: 5,
    name: "Rohan Deshmukh",
    email: "rohan.qc@awasio.in",
    roles: ["QC_REVIEWER"],
    status: "ACTIVE",
    mfaEnabled: true,
    lastLoginAt: "2026-09-30T11:50:00Z",
    createdAt: "2026-03-20T09:15:00Z",
  },
  {
    id: 6,
    name: "Meera Nair",
    email: "meera.catalog@awasio.in",
    roles: ["CATALOG_SPECIALIST", "QC_REVIEWER"],
    status: "ACTIVE",
    mfaEnabled: true,
    lastLoginAt: "2026-09-30T11:10:00Z",
    createdAt: "2026-04-01T10:00:00Z",
  },
  {
    id: 7,
    name: "Neha Gupta",
    email: "neha.verify@awasio.in",
    roles: ["VERIFICATION_SPECIALIST"],
    status: "ACTIVE",
    mfaEnabled: true,
    lastLoginAt: "2026-09-30T10:45:00Z",
    createdAt: "2026-04-05T08:45:00Z",
  },
  {
    id: 8,
    name: "Aditya Kapoor",
    email: "aditya.legal@awasio.in",
    roles: ["LEGAL_COMPLIANCE_OFFICER", "VERIFICATION_SPECIALIST"],
    status: "ACTIVE",
    mfaEnabled: true,
    lastLoginAt: "2026-09-30T10:00:00Z",
    createdAt: "2026-04-08T09:30:00Z",
  },
  {
    id: 9,
    name: "Sameer Khan",
    email: "sameer.fraud@awasio.in",
    roles: ["FRAUD_INVESTIGATOR"],
    status: "ACTIVE",
    mfaEnabled: true,
    lastLoginAt: "2026-09-30T09:40:00Z",
    createdAt: "2026-04-10T11:20:00Z",
  },
  {
    id: 10,
    name: "Karan Johar",
    email: "karan.support@awasio.in",
    roles: ["SUPPORT_EXECUTIVE"],
    status: "ACTIVE",
    mfaEnabled: true,
    lastLoginAt: "2026-09-30T08:10:00Z",
    createdAt: "2026-05-20T12:10:00Z",
  },
  {
    id: 11,
    name: "Sunil Verma",
    email: "sunil.finance@awasio.in",
    roles: ["FINANCE_EXECUTIVE", "FINANCE_APPROVER"],
    status: "ACTIVE",
    mfaEnabled: true,
    lastLoginAt: "2026-09-30T09:20:00Z",
    createdAt: "2026-04-12T14:20:00Z",
  },
  {
    id: 12,
    name: "Dr. Vikram Seth",
    email: "vikram.audit@awasio.in",
    roles: ["ANALYST_AUDITOR"],
    status: "ACTIVE",
    mfaEnabled: true,
    lastLoginAt: "2026-09-30T07:00:00Z",
    createdAt: "2026-06-01T09:00:00Z",
  },
];

export const INITIAL_PROPERTY_QC_QUEUE: PropertyQcItem[] = [
  {
    id: 16,
    title: "Luxury 3BHK Penthouse - City Reality",
    description: "Spacious luxury penthouse in South Delhi with private terrace and skyline views.",
    listingType: "SELL",
    resCom: "RESIDENTIAL",
    postedAs: "AGENT",
    price: 27500000,
    cityName: "New Delhi",
    locality: "Chhatarpur",
    address: "DLF Farms, Chhatarpur, New Delhi",
    carpetArea: 2400,
    carpetAreaUnit: "SQ_FT",
    bedrooms: 3,
    bathrooms: 3,
    furnishing: "SEMI_FURNISHED",
    ownershipType: "FREEHOLD",
    availabilityStatus: "READY_TO_MOVE",
    qcStatus: "UNDER_REVIEW",
    ownerType: "ORGANIZATION",
    organizationId: 1,
    organizationName: "City Reality",
    createdById: 1,
    creatorName: "VINAY ROY",
    creatorPhone: "8848510629",
    createdAt: "2026-09-30T14:25:34Z",
    updatedAt: "2026-09-30T14:25:34Z",
    media: [
      { id: 101, url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200", type: "IMAGE" },
      { id: 102, url: "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=1200", type: "IMAGE" },
    ],
    duplicateSuspected: false,
  },
  {
    id: 17,
    title: "Grade A Commercial Corporate Office",
    description: "Fully furnished commercial office with 60 workstations, 4 cabins, and boardroom.",
    listingType: "RENT",
    resCom: "COMMERCIAL",
    postedAs: "AGENT",
    price: 250000,
    cityName: "Gurugram",
    locality: "Cyber City",
    address: "DLF Cyber City Phase 2, Gurugram",
    carpetArea: 3200,
    carpetAreaUnit: "SQ_FT",
    ownershipType: "LEASEHOLD",
    availabilityStatus: "READY_TO_MOVE",
    qcStatus: "SUBMITTED",
    ownerType: "ORGANIZATION",
    organizationId: 1,
    organizationName: "City Reality",
    createdById: 7,
    creatorName: "Priya Singh",
    creatorPhone: "8848510633",
    createdAt: "2026-09-30T14:25:58Z",
    updatedAt: "2026-09-30T14:25:58Z",
    media: [
      { id: 104, url: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200", type: "IMAGE" },
    ],
    duplicateSuspected: false,
  },
  {
    id: 18,
    title: "Modern 2BHK Premium Apartment",
    description: "Bright and airy apartment close to metro station with modern modular kitchen.",
    listingType: "SELL",
    resCom: "RESIDENTIAL",
    postedAs: "AGENT",
    price: 9500000,
    cityName: "Noida",
    locality: "Sector 62",
    address: "Tower B, Sector 62, Noida",
    carpetArea: 1150,
    carpetAreaUnit: "SQ_FT",
    bedrooms: 2,
    bathrooms: 2,
    ownershipType: "FREEHOLD",
    availabilityStatus: "READY_TO_MOVE",
    qcStatus: "APPROVED",
    qcNotes: "Verified layout and ownership registry docs.",
    qcReviewerName: "Anjali Mehta",
    reviewedAt: "2026-09-30T15:00:00Z",
    ownerType: "ORGANIZATION",
    organizationId: 1,
    organizationName: "City Reality",
    createdById: 7,
    creatorName: "Priya Singh",
    creatorPhone: "8848510633",
    createdAt: "2026-09-30T14:25:58Z",
    updatedAt: "2026-09-30T15:00:00Z",
    media: [
      { id: 106, url: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200", type: "IMAGE" },
    ],
    duplicateSuspected: false,
  },
  {
    id: 19,
    title: "Suspicious 4BHK Villa in Vasant Kunj (Rate Anomaly)",
    description: "Ultra cheap luxury villa in South Delhi.",
    listingType: "SELL",
    resCom: "RESIDENTIAL",
    postedAs: "OWNER",
    price: 3500000,
    cityName: "New Delhi",
    locality: "Vasant Kunj",
    address: "Pocket 2, Vasant Kunj, New Delhi",
    carpetArea: 3500,
    carpetAreaUnit: "SQ_FT",
    bedrooms: 4,
    bathrooms: 4,
    qcStatus: "CHANGES_REQUESTED",
    qcNotes: "Price is unnaturally low for a 4BHK villa in Vasant Kunj. Please provide authentic property tax slip or revised rate.",
    qcReviewerName: "Rajesh Sharma",
    reviewedAt: "2026-09-30T11:15:00Z",
    ownerType: "PERSONAL",
    createdById: 12,
    creatorName: "Amit Kumar",
    creatorPhone: "9988776655",
    createdAt: "2026-09-30T10:00:00Z",
    updatedAt: "2026-09-30T11:15:00Z",
    media: [
      { id: 107, url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200", type: "IMAGE" },
    ],
    duplicateSuspected: true,
  },
];

export const INITIAL_ORG_VERIFICATIONS: OrgVerificationItem[] = [
  {
    id: 1,
    name: "City Reality Agency",
    type: "AGENCY",
    address: "DLF Farms, Chhatarpur, New Delhi",
    countryCode: "IN",
    ownerName: "VINAY ROY",
    ownerPhone: "8848510629",
    ownerEmail: "vinay@cityreality.in",
    verificationStatus: "VERIFIED",
    verificationNotes: "GSTIN and RERA certificate successfully cross-verified with official registry.",
    assignedSpecialistName: "Neha Gupta",
    verifiedAt: "2026-09-30T14:30:00Z",
    documents: [
      {
        id: "DOC-1",
        type: "GST_CERTIFICATE",
        documentNumber: "07AAACG1234F1Z5",
        fileUrl: "https://placehold.co/800x600/png?text=GST+Certificate+Verified",
        verified: true,
        expiresAt: "2028-12-31",
      },
      {
        id: "DOC-2",
        type: "RERA_REGISTRATION",
        documentNumber: "DLRERA2024A0091",
        fileUrl: "https://placehold.co/800x600/png?text=RERA+Registration+Approved",
        verified: true,
        expiresAt: "2029-06-30",
      },
    ],
    activePlan: "Concierge Tier",
    seatsUsed: 5,
    seatsLimit: 20,
    contactCredits: 100,
    listingsCount: 5,
    createdAt: "2026-09-30T12:10:17Z",
  },
  {
    id: 2,
    name: "Apex Prime Developers",
    type: "BUILDER",
    address: "Golf Course Road, Sector 54, Gurugram",
    countryCode: "IN",
    ownerName: "Siddharth Goel",
    ownerPhone: "9811223344",
    ownerEmail: "contact@apexprime.com",
    verificationStatus: "PENDING_REVIEW",
    documents: [
      {
        id: "DOC-3",
        type: "INCORPORATION",
        documentNumber: "U70100HR2021PTC099812",
        fileUrl: "https://placehold.co/800x600/png?text=Certificate+of+Incorporation",
        verified: false,
      },
      {
        id: "DOC-4",
        type: "RERA_REGISTRATION",
        documentNumber: "HRERA-PKL-998-2023",
        fileUrl: "https://placehold.co/800x600/png?text=HRERA+License+Copy",
        verified: false,
      },
    ],
    activePlan: "Enterprise Builder",
    seatsUsed: 2,
    seatsLimit: 15,
    contactCredits: 50,
    listingsCount: 8,
    createdAt: "2026-09-29T10:00:00Z",
  },
];

export const INITIAL_USER_ACCOUNTS: UserAccountItem[] = [
  {
    id: 1,
    name: "VINAY ROY",
    mobileNumber: "8848510629",
    email: "vinay@cityreality.in",
    status: "ACTIVE",
    isKycVerified: true,
    credits: 5,
    listingsCount: 1,
    organizationsCount: 2,
    totalSpent: 2499,
    createdAt: "2026-09-30T12:00:00Z",
    lastLoginAt: "2026-09-30T14:24:00Z",
  },
  {
    id: 7,
    name: "Priya Singh",
    mobileNumber: "8848510633",
    email: "priya.s@cityreality.in",
    status: "ACTIVE",
    isKycVerified: true,
    credits: 0,
    listingsCount: 2,
    organizationsCount: 1,
    totalSpent: 0,
    createdAt: "2026-09-30T14:25:00Z",
  },
  {
    id: 15,
    name: "Spammer Account 99",
    mobileNumber: "9123456780",
    email: "fake@spammer.net",
    status: "SUSPENDED",
    isKycVerified: false,
    credits: 0,
    listingsCount: 0,
    organizationsCount: 0,
    totalSpent: 0,
    createdAt: "2026-09-25T08:00:00Z",
    suspensionReason: "Repeated posting of duplicate fake rental listings.",
  },
];

export const INITIAL_BILLING_ORDERS: AdminBillingOrder[] = [
  {
    id: "ORD-98211",
    orderNumber: "CH-2026-09-98211",
    scope: "ORGANIZATION",
    targetId: 1,
    targetName: "City Reality Agency",
    planName: "Concierge Subscription (100 Contacts + RM)",
    amount: 2499,
    currency: "INR",
    status: "SUCCESS",
    paymentMethod: "RAZORPAY",
    gatewayPaymentId: "pay_PkN91aZ01m8s",
    createdAt: "2026-09-30T14:24:49Z",
    creditsAdded: 100,
  },
  {
    id: "ORD-98190",
    orderNumber: "CH-2026-09-98190",
    scope: "PERSONAL",
    targetId: 1,
    targetName: "VINAY ROY",
    planName: "Power Pack (20 Contacts)",
    amount: 499,
    currency: "INR",
    status: "SUCCESS",
    paymentMethod: "UPI",
    gatewayPaymentId: "pay_PjK882Lz9811",
    createdAt: "2026-09-29T18:10:00Z",
    creditsAdded: 20,
  },
];

export const INITIAL_REFUND_CASES: AdminRefundCase[] = [
  {
    id: "REF-001",
    orderNumber: "CH-2026-09-98190",
    targetName: "VINAY ROY",
    amount: 499,
    requestedById: 8,
    requestedBy: "Karan Johar (Support)",
    reason: "Customer was charged twice due to bank gateway timeout.",
    status: "PENDING_APPROVAL",
    approverRequiredRole: "FINANCE_APPROVER",
    createdAt: "2026-09-30T16:00:00Z",
  },
];

export const INITIAL_DISPUTE_CASES: AdminDisputeCase[] = [
  {
    id: "DSP-1001",
    caseNumber: "CASE-2026-09-1001",
    type: "INVALID_CONTACT",
    propertyId: 19,
    propertyTitle: "Suspicious 4BHK Villa in Vasant Kunj",
    complainantName: "Dr. Arvind Saxena",
    complainantPhone: "+91 9876543210",
    respondentName: "Amit Kumar",
    chargedAccount: "PERSONAL",
    assignedTo: "Karan Johar",
    status: "IN_PROGRESS",
    priority: "HIGH",
    refundRequested: true,
    notes: "Buyer unlocked owner contact; number is switched off and locality was misrepresented.",
    createdAt: "2026-09-30T11:30:00Z",
    updatedAt: "2026-09-30T12:00:00Z",
  },
  {
    id: "DSP-1002",
    caseNumber: "CASE-2026-09-1002",
    type: "UNAUTHORIZED_LISTING",
    propertyId: 16,
    propertyTitle: "Luxury 3BHK Penthouse - City Reality",
    complainantName: "Sunita Kapoor (Original Owner)",
    complainantPhone: "+91 9811229988",
    respondentName: "City Reality Agency",
    chargedAccount: "ORGANIZATION",
    assignedTo: "Rajesh Sharma",
    status: "WAITING",
    priority: "URGENT",
    refundRequested: false,
    notes: "Owner claims broker listed property without written mandate. Broker asked to upload agreement copy.",
    createdAt: "2026-09-29T16:45:00Z",
    updatedAt: "2026-09-30T09:15:00Z",
  },
  {
    id: "DSP-1003",
    caseNumber: "CASE-2026-09-1003",
    type: "PAYMENT_ISSUE",
    complainantName: "Manish Tiwari",
    complainantPhone: "+91 9988112233",
    chargedAccount: "PERSONAL",
    assignedTo: "Sunil Verma",
    status: "RESOLVED",
    priority: "MEDIUM",
    refundRequested: true,
    notes: "UPI debited ₹499 but 20 contact credits were delayed. Credits manually credited + 5 courtesy credits added.",
    createdAt: "2026-09-28T14:00:00Z",
    updatedAt: "2026-09-29T10:30:00Z",
  },
];

export const INITIAL_CONTACT_UNLOCKS: AdminContactUnlockTrace[] = [
  {
    id: "TRC-891",
    propertyId: 18,
    propertyTitle: "Modern 2BHK Premium Apartment",
    buyerName: "Deepak Choudhury",
    buyerPhone: "+91 9810293847",
    chargedScope: "PERSONAL",
    chargedEntityName: "Deepak Choudhury",
    responsibleStaffOrMember: "Direct Buyer",
    creditsDeducted: 1,
    isDuplicateSuppressed: false,
    unlockedAt: "2026-09-30T15:20:00Z",
  },
  {
    id: "TRC-892",
    propertyId: 16,
    propertyTitle: "Luxury 3BHK Penthouse - City Reality",
    buyerName: "Kavita Singhal",
    buyerPhone: "+91 9871234567",
    chargedScope: "ORGANIZATION",
    chargedEntityName: "Prime Realtors Co.",
    responsibleStaffOrMember: "Agent Rohit (Seat #3)",
    creditsDeducted: 1,
    isDuplicateSuppressed: false,
    unlockedAt: "2026-09-30T14:50:00Z",
  },
  {
    id: "TRC-893",
    propertyId: 18,
    propertyTitle: "Modern 2BHK Premium Apartment",
    buyerName: "Deepak Choudhury",
    buyerPhone: "+91 9810293847",
    chargedScope: "PERSONAL",
    chargedEntityName: "Deepak Choudhury",
    responsibleStaffOrMember: "Direct Buyer",
    creditsDeducted: 0,
    isDuplicateSuppressed: true,
    unlockedAt: "2026-09-30T15:35:00Z",
  },
];

export const INITIAL_FRAUD_ALERTS: AdminFraudAlert[] = [
  {
    id: "FRD-301",
    severity: "HIGH",
    category: "DUPLICATE_CLUSTER",
    title: "Suspicious Coordinate Duplication (4 Listings)",
    description: "4 listings with differing prices posted within identical 50m geofence in Sector 62, Noida.",
    targetId: 18,
    targetType: "PROPERTY",
    detectedAt: "2026-09-30T13:45:00Z",
    status: "INVESTIGATING",
  },
  {
    id: "FRD-302",
    severity: "CRITICAL",
    category: "ABNORMAL_SCRAPING",
    title: "High Velocity Contact Unlock (>15 in 2 mins)",
    description: "User account #15 attempted automated contact harvesting. Rate limiter triggered and account auto-quarantined.",
    targetId: 15,
    targetType: "USER",
    detectedAt: "2026-09-25T08:00:00Z",
    status: "RESOLVED",
  },
];

export const INITIAL_AUDIT_LOGS: AdminAuditLog[] = [
  {
    id: "AUD-101",
    actorId: 1,
    actorName: "Vinay Kumar",
    actorEmail: "vinay.admin@awasio.in",
    actorRole: "SUPER_ADMIN",
    action: "STAFF_ROLE_ASSIGNED",
    targetType: "STAFF",
    targetId: 5,
    targetName: "Sunil Verma",
    reason: "Assigned FINANCE_APPROVER role for Q4 refund workflow.",
    createdAt: "2026-09-30T14:00:00Z",
  },
  {
    id: "AUD-102",
    actorId: 4,
    actorName: "Neha Gupta",
    actorEmail: "neha.verify@awasio.in",
    actorRole: "VERIFICATION_SPECIALIST",
    action: "ORGANIZATION_VERIFIED",
    targetType: "ORGANIZATION",
    targetId: 1,
    targetName: "City Reality Agency",
    reason: "All RERA and GST documents verified with registry.",
    createdAt: "2026-09-30T13:30:00Z",
  },
  {
    id: "AUD-103",
    actorId: 3,
    actorName: "Anjali Mehta",
    actorEmail: "anjali.qc@awasio.in",
    actorRole: "QC_REVIEWER",
    action: "PROPERTY_QC_APPROVED",
    targetType: "PROPERTY",
    targetId: 18,
    targetName: "Modern 2BHK Premium Apartment",
    reason: "Passed all title and photo resolution checks.",
    createdAt: "2026-09-30T12:00:00Z",
  },
];
