/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports all enum related types from the schema.
 *
 * 🟢 You can import this file directly.
 */

export const ListingType = {
  RENT: "RENT",
  SELL: "SELL",
  PG: "PG",
} as const;

export type ListingType = (typeof ListingType)[keyof typeof ListingType];

export const PropertyStatus = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  SOLD: "SOLD",
  RENTED: "RENTED",
  DRAFT: "DRAFT",
  ARCHIVED: "ARCHIVED",
} as const;

export type PropertyStatus =
  (typeof PropertyStatus)[keyof typeof PropertyStatus];

export const FurnishingType = {
  UNFURNISHED: "UNFURNISHED",
  SEMI_FURNISHED: "SEMI_FURNISHED",
  FULLY_FURNISHED: "FULLY_FURNISHED",
} as const;

export type FurnishingType =
  (typeof FurnishingType)[keyof typeof FurnishingType];

export const Facing = {
  NORTH: "NORTH",
  SOUTH: "SOUTH",
  EAST: "EAST",
  WEST: "WEST",
  NORTH_EAST: "NORTH_EAST",
  NORTH_WEST: "NORTH_WEST",
  SOUTH_EAST: "SOUTH_EAST",
  SOUTH_WEST: "SOUTH_WEST",
} as const;

export type Facing = (typeof Facing)[keyof typeof Facing];

export const PossessionStatus = {
  READY_TO_MOVE: "READY_TO_MOVE",
  UNDER_CONSTRUCTION: "UNDER_CONSTRUCTION",
  LAUNCH: "LAUNCH",
} as const;

export type PossessionStatus =
  (typeof PossessionStatus)[keyof typeof PossessionStatus];

export const OwnershipType = {
  FREEHOLD: "FREEHOLD",
  LEASEHOLD: "LEASEHOLD",
  CO_OPERATIVE: "CO_OPERATIVE",
} as const;

export type OwnershipType = (typeof OwnershipType)[keyof typeof OwnershipType];

export const TransactionType = {
  CREDIT_PURCHASE: "CREDIT_PURCHASE",
  PROPERTY_VIEW: "PROPERTY_VIEW",
  SUBSCRIPTION: "SUBSCRIPTION",
  REFUND: "REFUND",
} as const;

export type TransactionType =
  (typeof TransactionType)[keyof typeof TransactionType];

export const MediaType = {
  IMAGE: "IMAGE",
  VIDEO: "VIDEO",
  VIRTUAL_TOUR: "VIRTUAL_TOUR",
  VOICE_OVER: "VOICE_OVER",
  OTHER: "OTHER",
} as const;

export type MediaType = (typeof MediaType)[keyof typeof MediaType];

export const AvailabilityStatus = {
  READY_TO_MOVE: "READY_TO_MOVE",
  UNDER_CONSTRUCTION: "UNDER_CONSTRUCTION",
  POSSESSION_SOON: "POSSESSION_SOON",
  NEW_LAUNCH: "NEW_LAUNCH",
} as const;

export type AvailabilityStatus =
  (typeof AvailabilityStatus)[keyof typeof AvailabilityStatus];

export const AgeOfProperty = {
  ZERO_TO_ONE: "ZERO_TO_ONE",
  ONE_TO_FIVE: "ONE_TO_FIVE",
  FIVE_TO_TEN: "FIVE_TO_TEN",
  TEN_PLUS: "TEN_PLUS",
} as const;

export type AgeOfProperty = (typeof AgeOfProperty)[keyof typeof AgeOfProperty];

export const MaintenancePeriod = {
  MONTHLY: "MONTHLY",
  ANNUALLY: "ANNUALLY",
} as const;

export type MaintenancePeriod =
  (typeof MaintenancePeriod)[keyof typeof MaintenancePeriod];

export const PaymentFrequency = {
  ONE_TIME: "ONE_TIME",
  MONTHLY: "MONTHLY",
  QUARTERLY: "QUARTERLY",
  HALF_YEARLY: "HALF_YEARLY",
  ANNUALLY: "ANNUALLY",
} as const;

export type PaymentFrequency =
  (typeof PaymentFrequency)[keyof typeof PaymentFrequency];

export const AreaUnit = {
  SQ_FT: "SQ_FT",
  SQ_M: "SQ_M",
  BIGHA: "BIGHA",
  KOTTAH: "KOTTAH",
  GROUNDS: "GROUNDS",
  ARES: "ARES",
  BISWA: "BISWA",
  GUNTHA: "GUNTHA",
  AANKADAM: "AANKADAM",
  HECTARES: "HECTARES",
  CENTS: "CENTS",
  PERCH: "PERCH",
} as const;

export type AreaUnit = (typeof AreaUnit)[keyof typeof AreaUnit];

export const PossessionType = {
  WITHIN_3_MONTHS: "WITHIN_3_MONTHS",
  WITHIN_6_MONTHS: "WITHIN_6_MONTHS",
  BY_2027: "BY_2027",
  BY_2028: "BY_2028",
  BY_2029: "BY_2029",
} as const;

export type PossessionType =
  (typeof PossessionType)[keyof typeof PossessionType];

export const months = {
  JANUARY: "JANUARY",
  FEBRUARY: "FEBRUARY",
  MARCH: "MARCH",
  APRIL: "APRIL",
  MAY: "MAY",
  JUNE: "JUNE",
  JULY: "JULY",
  AUGUST: "AUGUST",
  SEPTEMBER: "SEPTEMBER",
  OCTOBER: "OCTOBER",
  NOVEMBER: "NOVEMBER",
  DECEMBER: "DECEMBER",
} as const;

export type months = (typeof months)[keyof typeof months];

export const PropertyZoneType = {
  INDUSTRIAL: "INDUSTRIAL",
  COMMERCIAL: "COMMERCIAL",
  RESIDENTIAL: "RESIDENTIAL",
  TRANSPORT_AND_COMMUNICATION: "TRANSPORT_AND_COMMUNICATION",
  PUBLIC_UTILITIES: "PUBLIC_UTILITIES",
  PUBLIC_AND_SEMI_PUBLIC_USE: "PUBLIC_AND_SEMI_PUBLIC_USE",
  OPEN_SPACES: "OPEN_SPACES",
  AGRICULTURAL_ZONE: "AGRICULTURAL_ZONE",
  SPECIAL_ECONOMIC_ZONE: "SPECIAL_ECONOMIC_ZONE",
  NATURAL_CONSERVATION_ZONE: "NATURAL_CONSERVATION_ZONE",
  GOVERNMENT_USE: "GOVERNMENT_USE",
  OTHER: "OTHER",
} as const;

export type PropertyZoneType =
  (typeof PropertyZoneType)[keyof typeof PropertyZoneType];

export const MeasurementUnit = {
  FEET: "FEET",
  METER: "METER",
} as const;

export type MeasurementUnit =
  (typeof MeasurementUnit)[keyof typeof MeasurementUnit];

export const PropertyOnFloor = {
  LOWER_BASEMENT: "LOWER_BASEMENT",
  BASEMENT: "BASEMENT",
  LOWER_GROUND: "LOWER_GROUND",
  GROUND: "GROUND",
  ROOFTOP_TERRACE: "ROOFTOP_TERRACE",
  FLOOR_1: "FLOOR_1",
  FLOOR_2: "FLOOR_2",
  FLOOR_3: "FLOOR_3",
  FLOOR_4: "FLOOR_4",
  FLOOR_5: "FLOOR_5",
  FLOOR_6: "FLOOR_6",
  FLOOR_7: "FLOOR_7",
  FLOOR_8: "FLOOR_8",
  FLOOR_9: "FLOOR_9",
  FLOOR_10: "FLOOR_10",
  FLOOR_11: "FLOOR_11",
  FLOOR_12: "FLOOR_12",
  FLOOR_13: "FLOOR_13",
  FLOOR_14: "FLOOR_14",
  FLOOR_15: "FLOOR_15",
  FLOOR_16: "FLOOR_16",
  FLOOR_17: "FLOOR_17",
  FLOOR_18: "FLOOR_18",
  FLOOR_19: "FLOOR_19",
  FLOOR_20: "FLOOR_20",
} as const;

export type PropertyOnFloor =
  (typeof PropertyOnFloor)[keyof typeof PropertyOnFloor];

export const Rating = {
  NO_RATING: "NO_RATING",
  ONE_STAR: "ONE_STAR",
  TWO_STAR: "TWO_STAR",
  THREE_STAR: "THREE_STAR",
  FOUR_STAR: "FOUR_STAR",
  FIVE_STAR: "FIVE_STAR",
  SIX_STAR: "SIX_STAR",
  SEVEN_STAR: "SEVEN_STAR",
} as const;

export type Rating = (typeof Rating)[keyof typeof Rating];

export const PropertyRole = {
  OWNER: "OWNER",
  AGENT: "AGENT",
  BUYER: "BUYER",
  TENANT: "TENANT",
  SELLER: "SELLER",
} as const;

export type PropertyRole = (typeof PropertyRole)[keyof typeof PropertyRole];

export const QcStatus = {
  NOT_REQUIRED: "NOT_REQUIRED",
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
} as const;

export type QcStatus = (typeof QcStatus)[keyof typeof QcStatus];

export const DocumentType = {
  ID_PROOF: "ID_PROOF",
  ADDRESS_PROOF: "ADDRESS_PROOF",
  OWNERSHIP_PROOF: "OWNERSHIP_PROOF",
  RENTAL_AGREEMENT: "RENTAL_AGREEMENT",
  OTHER: "OTHER",
} as const;

export type DocumentType = (typeof DocumentType)[keyof typeof DocumentType];

export const AgreementStatus = {
  ACTIVE: "ACTIVE",
  ENDED: "ENDED",
  CANCELLED: "CANCELLED",
} as const;

export type AgreementStatus =
  (typeof AgreementStatus)[keyof typeof AgreementStatus];

export const KycDocumentType = {
  PAN: "PAN",
  AADHAAR: "AADHAAR",
  PASSPORT: "PASSPORT",
  RERA: "RERA",
  GST: "GST",
  OTHER: "OTHER",
} as const;

export type KycDocumentType =
  (typeof KycDocumentType)[keyof typeof KycDocumentType];

export const KycStatus = {
  PENDING: "PENDING",
  UNDER_REVIEW: "UNDER_REVIEW",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
} as const;

export type KycStatus = (typeof KycStatus)[keyof typeof KycStatus];

export const LeadStatus = {
  NEW: "NEW",
  CONTACTED: "CONTACTED",
  VISIT_SCHEDULED: "VISIT_SCHEDULED",
  OFFER_MADE: "OFFER_MADE",
  CLOSED_WON: "CLOSED_WON",
  CLOSED_LOST: "CLOSED_LOST",
} as const;

export type LeadStatus = (typeof LeadStatus)[keyof typeof LeadStatus];

export const LeadSource = {
  ORGANIC: "ORGANIC",
  PAID: "PAID",
  WHATSAPP: "WHATSAPP",
  CALL: "CALL",
  DIRECT: "DIRECT",
  OTHER: "OTHER",
} as const;

export type LeadSource = (typeof LeadSource)[keyof typeof LeadSource];

export const LeadTag = {
  HOT: "HOT",
  WARM: "WARM",
  COLD: "COLD",
} as const;

export type LeadTag = (typeof LeadTag)[keyof typeof LeadTag];

export const VisitStatus = {
  SCHEDULED: "SCHEDULED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  NO_SHOW: "NO_SHOW",
} as const;

export type VisitStatus = (typeof VisitStatus)[keyof typeof VisitStatus];

export const ConversationType = {
  INQUIRY: "INQUIRY",
  SUPPORT: "SUPPORT",
} as const;

export type ConversationType =
  (typeof ConversationType)[keyof typeof ConversationType];

export const ParticipantRole = {
  BUYER: "BUYER",
  AGENT: "AGENT",
  OWNER: "OWNER",
  SUPPORT: "SUPPORT",
} as const;

export type ParticipantRole =
  (typeof ParticipantRole)[keyof typeof ParticipantRole];

export const MessageType = {
  TEXT: "TEXT",
  IMAGE: "IMAGE",
  SYSTEM: "SYSTEM",
} as const;

export type MessageType = (typeof MessageType)[keyof typeof MessageType];

export const NotificationType = {
  NEW_LEAD: "NEW_LEAD",
  LEAD_STATUS_UPDATE: "LEAD_STATUS_UPDATE",
  KYC_STATUS_UPDATE: "KYC_STATUS_UPDATE",
  PROPERTY_APPROVED: "PROPERTY_APPROVED",
  PROPERTY_REJECTED: "PROPERTY_REJECTED",
  SUBSCRIPTION_EXPIRY: "SUBSCRIPTION_EXPIRY",
  OTHER: "OTHER",
} as const;

export type NotificationType =
  (typeof NotificationType)[keyof typeof NotificationType];

export const ReviewTargetType = {
  USER: "USER",
  PROPERTY: "PROPERTY",
  PROJECT: "PROJECT",
} as const;

export type ReviewTargetType =
  (typeof ReviewTargetType)[keyof typeof ReviewTargetType];

export const ReviewStatus = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
} as const;

export type ReviewStatus = (typeof ReviewStatus)[keyof typeof ReviewStatus];

export const ReportTargetType = {
  USER: "USER",
  PROPERTY: "PROPERTY",
  MESSAGE: "MESSAGE",
} as const;

export type ReportTargetType =
  (typeof ReportTargetType)[keyof typeof ReportTargetType];

export const ReportStatus = {
  OPEN: "OPEN",
  IN_REVIEW: "IN_REVIEW",
  RESOLVED: "RESOLVED",
  DISMISSED: "DISMISSED",
} as const;

export type ReportStatus = (typeof ReportStatus)[keyof typeof ReportStatus];

export const PlanBillingCycle = {
  MONTHLY: "MONTHLY",
  QUARTERLY: "QUARTERLY",
  YEARLY: "YEARLY",
} as const;

export type PlanBillingCycle =
  (typeof PlanBillingCycle)[keyof typeof PlanBillingCycle];

export const CreditReason = {
  PURCHASE: "PURCHASE",
  BONUS: "BONUS",
  CONTACT_UNLOCK: "CONTACT_UNLOCK",
  PROPERTY_BOOST: "PROPERTY_BOOST",
  EXPIRY: "EXPIRY",
  ADJUSTMENT: "ADJUSTMENT",
} as const;

export type CreditReason = (typeof CreditReason)[keyof typeof CreditReason];

export const SubscriptionStatus = {
  ACTIVE: "ACTIVE",
  EXPIRED: "EXPIRED",
  CANCELLED: "CANCELLED",
  PAST_DUE: "PAST_DUE",
} as const;

export type SubscriptionStatus =
  (typeof SubscriptionStatus)[keyof typeof SubscriptionStatus];

export const PropertyOwnerType = {
  USER: "USER",
  ORGANIZATION: "ORGANIZATION",
} as const;

export type PropertyOwnerType =
  (typeof PropertyOwnerType)[keyof typeof PropertyOwnerType];
